[2024-04-05 17:14:29,723][urllib3.connectionpool][WARNING] - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x101568d30>: Failed to resolve 'o151352.ingest.sentry.io' ([Errno 8] nodename nor servname provided, or not known)")': /api/4504800232407040/envelope/
[2024-04-05 17:14:29,724][urllib3.connectionpool][WARNING] - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x13ae58280>: Failed to resolve 'o151352.ingest.sentry.io' ([Errno 8] nodename nor servname provided, or not known)")': /api/4504800232407040/envelope/
[2024-04-05 17:14:29,725][urllib3.connectionpool][WARNING] - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x13ae58070>: Failed to resolve 'o151352.ingest.sentry.io' ([Errno 8] nodename nor servname provided, or not known)")': /api/4504800232407040/envelope/
[2024-04-05 17:14:29,726][urllib3.connectionpool][WARNING] - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x10156a9b0>: Failed to resolve 'o151352.ingest.sentry.io' ([Errno 8] nodename nor servname provided, or not known)")': /api/4504800232407040/envelope/
[2024-04-05 17:14:29,726][urllib3.connectionpool][WARNING] - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x10156ab60>: Failed to resolve 'o151352.ingest.sentry.io' ([Errno 8] nodename nor servname provided, or not known)")': /api/4504800232407040/envelope/
[2024-04-05 17:14:29,727][urllib3.connectionpool][WARNING] - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x10156ad10>: Failed to resolve 'o151352.ingest.sentry.io' ([Errno 8] nodename nor servname provided, or not known)")': /api/4504800232407040/envelope/
